### ISSUE TITLE
Error in Example command.

### ISSUE THREAD

**Issue by alexfornuto** [drio/tsmetrics#1]
After running the example command from the readme:

```
flag provided but not defined: -tsnet-verbose
Usage of /tmp/go-build3382925821/b001/exe/tsmetrics:
  -addr string
    	address to listen on (default ":9100")
  -hostname string
    	hostname to use on the tailnet (metrics) (default "metrics")
  -regular-server
    	use to create a normal http server
  -resolve-names
    	convert tailscale IP addresses to hostnames
  -wait-secs int
    	waiting time after getting new data (default 45)
exit status
```

**Comment by alexfornuto** [comment]
Running without it:

```
2024/11/04 20:16:15 Please, provide a OAUTH_CLIENT_ID option
exit status 1
```

OAUTH_CLIENT_ID is defined in `.env`. It needs to be manually added to the environment running the command, which is also not documented.

**Comment by drio** [comment]
@alexfornuto  Thank you for the feedback. 

Here is how I am running it:

```
$ cat .env
OAUTH_CLIENT_ID=xxxxxx
OAUTH_CLIENT_SECRET=tskey-clientxxx
TAILNET_NAME=tailnetname

# This just sources the env and runs the command
$ make -n run
bash -c 'set -a; source <(cat .env | \
        sed "s/#.*//g" | xargs); \
        set +a && go run . --wait-secs=240 --tsnet-verbose --addr=:9100 --resolve-names'
```

If still fails, can you please show me your .env (remove credentials) and your exact cmd?

Thank you. Happy to improve the readme once we get this sorted out.

**Comment by drio** [comment]
Closing for now. Reopen if you are still having issues. Thank you.

**Comment by alexfornuto** [comment]
Using that command I was able to start the process, thought i still had to remove `--tsnet-verbose`.  Either way, the README needs to be updated as it doesn't work as written.

Also FYI:
![image](https://github.com/user-attachments/assets/ac1a7b17-7159-4315-8bea-029446ab9cc3)
At least one security patch has been issued in those last 8 releases.

P.S. I as an external party cannot reopen this issue.

**Comment by drio** [comment]
[README updated](https://github.com/drio/tsmetrics/commit/8b31f4cd2bbbbe112e9be8567b3e3e9f219bd6ec) and packages (and go runtime) [updated to latest version](https://github.com/drio/tsmetrics/commit/982c4ede3104464a91a53134d43e4d97679a2adb).

Thank you!
